# This script uses Selenium to make a screenshot of a COVID data visualization generated by a webpage.
# The webpage is generated via data on a Google spreadsheet (which, in turn, is updated by two other scripts here).
# The script then uploads that image to a server, where it's referenced in the daily newsletter.

from ftplib import FTP
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from pyvirtualdisplay import Display
import time
import os


# Initial variables for access and the virtual display.

FTPUSER = os.environ["FTPUSER"]
FTPPASS = os.environ["FTPPASS"]

display = Display(visible=0, size=(300,650))
display.start()


# Load the webpage on the virtual display and generate a screenshot.

def screenshotit():
    options = Options()
    options.headless = True
    browser = webdriver.Chrome(options=options)
    url = "https://kevinjbeaty.com/projects/dnvrite/COVID/covidwidget-simple-newdata.php"
    browser.get(url)
    content = browser.find_element('xpath','//*[@id="textarea"]')
    time.sleep(10)
    content.screenshot("./covidshot-simple.png")
    browser.close()
    uploadit()


# Upload the screenshot to a server via FTP.
    
def uploadit():
    ftp = FTP('ftp.kevinjbeaty.com')
    ftp.login(user=FTPUSER, passwd=FTPPASS)
    file = open('./covidshot-simple.png', 'rb')
    ftp.storbinary('STOR covidshot-simple.png', file)
    file.close()
    ftp.quit()


# Start the code!
    
screenshotit()
