name: Screenshot COVID Data
env:
  FTPUSER: ${{ secrets.FTPUSER }}
  FTPPASS: ${{ secrets.FTPPASS }}
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install webdriver-manager selenium PyVirtualDisplay
      - name: Run the script
        run: python covidScreenshotter.py
