name: Scrape DDPHE Violations
env:
  SLACKURL: ${{ secrets.slackURL }}
  CITYLOGIN: ${{ secrets.cityLogin }}
  LASTRECORD: "2025-DDPHEAC-0000011"
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install beautifulsoup4 webdriver_manager selenium PyVirtualDisplay
      - name: Run the script
        run: 
          python DdpheViolations.py
          echo "LASTRECORD=$LASTRECORD" >> $LASTRECORD
