name: Scrape DDPHE Violations
env:
  SLACKURL: ${{ secrets.slackURL }}
  CITYLOGIN: ${{ secrets.cityLogin }}
  LASTRECORD: "2025-DDPHEAC-0000011"
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install beautifulsoup4 webdriver_manager selenium PyVirtualDisplay
      - name: Run the script
        run: python DdpheViolations.py
      - name: Commit updated file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add DdpheViolationsLatestEntry.txt
          git commit -m "Update latest entry"
          git push
        continue-on-error: true
