name: Scrape Design Proposals
env:
  SLACKURL: ${{ secrets.slackURL }}
  CITYLOGIN: ${{ secrets.cityLogin }}
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install beautifulsoup4 webdriver_manager selenium
      - name: Run design proposals
        run: python DenverDesignProposals.py
      - name: Run demolitions
        run: DemolitionEligibility.py
      - name: Run large dev reviews
        run: LargeDevelopmentReviews.py
      - name: Run complaints
        run: BuildingComplaints.py
      - name: Run violations
        run: DdpheViolations.py
