name: Scrape Prices
env:
  PRICEKEY: ${{ secrets.TSAKEY }}
  PRIVATEKEY: ${{ secrets.PRIVATEKEY }}
  PRIVATEIDKEY: ${{ secrets.PRIVATEIDKEY }}
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install gspread webdriver-manager selenium PyVirtualDisplay
      - name: Run the script
        run: python TsaWaitTimesTracker.py.py
